shops:
  - type: ebay
    name: cozyboots
    param1: test
    param2: test
  - type: ebay
    name: cozyboots2
    param1: test
    param2: test
  - type: shopify 
    name: cozyshop
    param1: test
    param2: test