sentry: http://sentry.url
shops:
  - type: ebay
    name: cozyboots
    master: true
    config:
      param1: test
      param2: test
  - type: ebay
    name: cozyboots2
    config:
      param1: test
      param2: test
  - type: shopify 
    name: cozyshop
    config:
      param1: test
      param2: test